# Generated by Django 5.1 on 2024-09-02 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfmr_api_key', models.CharField(blank=True, max_length=255)),
                ('bfmr_api_secret', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buying_groups', models.CharField(blank=True, max_length=100)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('product', models.CharField(max_length=200)),
                ('merchant', models.CharField(blank=True, max_length=100)),
                ('card', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reimbursed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_back', models.DecimalField(decimal_places=2, default=0, help_text='Cash back percentage', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
