# Generated by Django 5.1 on 2024-09-12 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredentials',
            name='api_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='api_secret',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_group', models.CharField(blank=True, choices=[('', 'Select a buying group or enter your own'), ('USA Buying Group', 'USA Buying Group (https://usabuying.group/referred-by/JEROG21)'), ('BFMR', 'BFMR (https://bfmr.com)'), ('Big Sky Buying Group', 'Big Sky Buying Group (https://bigskybuyers.com)'), ('Deal & Runner', 'Deal & Runner (https://portal.dealandrunner.com/?a=UA5Z2)'), ('Buying Group', 'Buying Group (https://buyinggroup.com/signup?id=e26acdbb)'), ('CloseoutNJ', 'CloseoutNJ (https://www.closeoutnj.com/p/newaccount/_referral/eyJjdCI6InNyVm81MTR2dFQ5M3dUQVBzZEVoakE9PSIsIml2IjoiZGIyYWRlZDcwZjIyZThhMGVjOGFjOTFkMjdhNmZhMWMiLCJzIjoiOWNhM2VkZWJlMzAxYmJhMiJ9)'), ('Maxout Deals', 'Maxout Deals (https://www.maxoutdeals.com/p/newaccount/_referral/eyJjdCI6InRlc3l6TCtxRmVZemlZV1J2WVhuNGc9PSIsIml2IjoiNjVjMDY4YWU1MmVkNTcxMDMwZTNjMmEyMmQ5MzM0ZGEiLCJzIjoiNTk2Zjc3ODg1ODk5NjdlZCJ9)'), ('Other', 'Other (please specify)')], max_length=100)),
                ('custom_buying_group', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
