# Generated by Django 5.1 on 2024-09-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_account_alter_order_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_back',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='reimbursed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
