# Generated by Django 5.1 on 2024-09-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buyinggroup_order_buying_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyinggroup',
            name='fee_percentage',
        ),
        migrations.RemoveField(
            model_name='buyinggroup',
            name='notes',
        ),
    ]
