# Generated by Django 5.1 on 2024-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicredentials',
            name='bfmr_api_key',
        ),
        migrations.RemoveField(
            model_name='apicredentials',
            name='bfmr_api_secret',
        ),
        migrations.AddField(
            model_name='apicredentials',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apicredentials',
            name='api_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
