# Generated by Django 5.1 on 2024-09-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_apicredentials_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinggroup',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyinggroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='buyinggroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='buying_group',
            field=models.CharField(blank=True, choices=[('', 'Select a buying group or enter your own'), ('USA Buying Group', 'USA Buying Group (https://usabuying.group/referred-by/JEROG21)'), ('BFMR', 'BFMR (https://bfmr.com)'), ('Big Sky Buying Group', 'Big Sky Buying Group (https://bigskybuyers.com)'), ('Deal & Runner', 'Deal & Runner (https://portal.dealandrunner.com/?a=UA5Z2)'), ('Buying Group', 'Buying Group (https://buyinggroup.com/signup?id=e26acdbb)'), ('CloseoutNJ', 'CloseoutNJ (https://www.closeoutnj.com/p/newaccount/_referral/eyJjdCI6InNyVm81MTR2dFQ5MzdUQVBzZEVoakE9PSIsIml2IjoiZGIyYWRlZDcwZjIyZThhMGVjOGFjOTFkMjdhNmZhMWMiLCJzIjoiOWNhM2VkZWJlMzAxYmJhMiJ9)'), ('Maxout Deals', 'Maxout Deals (https://www.maxoutdeals.com/p/newaccount/_referral/eyJjdCI6InRlc3l6TCtxRmVZemlZV1J2WVhuNGc9PSIsIml2IjoiNjVjMDY4YWU1MmVkNTcxMDMwZTNjMmEyMmQ5MzM0ZGEiLCJzIjoiNTk2Zjc3ODg1ODk5NjdlZCJ9)'), ('Other', 'Other (please specify)')], max_length=100),
        ),
    ]
