# Generated by Django 5.1 on 2024-09-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_buyinggroup_predefined_alter_buyinggroup_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredentials',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='api_secret',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
