# Generated by Django 5.1 on 2024-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_buyinggroup_fee_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buying_groups',
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_back',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='merchant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
