# Generated by Django 5.1 on 2024-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_apicredentials_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyinggroup',
            name='referral_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyinggroup',
            name='referral_link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
