# Generated by Django 5.1 on 2024-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_account_alter_order_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_back',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
