# Generated by Django 5.1 on 2024-09-15 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PRO', 'Pro'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=10),
        ),
    ]
