# Generated by Django 5.1 on 2024-09-19 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_refresh_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
