# Generated by Django 5.1 on 2024-08-30 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buying_groups', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=200)),
                ('merchant', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reimbursed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'order_number')},
            },
        ),
    ]
