# Generated by Django 5.1 on 2024-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_back',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash back percentage', max_digits=5),
        ),
    ]
