# Generated by Django 5.1 on 2024-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_account_alter_order_buying_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='merchant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
