# Generated by Django 5.1 on 2024-09-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_apicredentials'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
